import json
from typing import Dict, Any, Optional

class DispatchInterface:
    """
    Interface for NPC Dispatch missions, designed for WebSocket communication with Unity.
    Provides standardized request and response formats.
    """

    @staticmethod
    def create_request(
        requester_npc: str,
        target_npc: str,
        player_request: str,
        inquiry_topic: str,
        relationship_to_player: float = 0.5,
        relationship_between_npcs: str = "Acquaintance",
        max_turns: int = 5
    ) -> Dict[str, Any]:
        """
        Creates a structured request for starting a dispatch mission.
        """
        return {
            "type": "dispatch_request",
            "payload": {
                "requester_npc": requester_npc,
                "target_npc": target_npc,
                "player_request": player_request,
                "inquiry_topic": inquiry_topic,
                "relationship_to_player": relationship_to_player,
                "relationship_between_npcs": relationship_between_npcs,
                "max_turns": max_turns
            }
        }

    @staticmethod
    def create_response(
        mission_id: str,
        is_accepted: bool,
        report: str,
        refusal_reason: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Creates a structured response for Unity.
        
        Args:
            mission_id: Unique ID for the mission.
            is_accepted: Whether the NPC accepted the dispatch request.
            report: The final report generated by the NPC (empty if refused).
            refusal_reason: Why the NPC refused (if applicable).
        """
        return {
            "type": "dispatch_response",
            "payload": {
                "mission_id": mission_id,
                "is_accepted": is_accepted,
                "report": report,
                "refusal_reason": refusal_reason
            }
        }

    @staticmethod
    def parse_unity_message(message_str: str) -> Dict[str, Any]:
        """
        Parses a JSON message from Unity.
        """
        try:
            return json.loads(message_str)
        except json.JSONDecodeError:
            return {"type": "error", "message": "Invalid JSON format"}
